project:
  type: website
  output-dir: docs

website:
  title: "i am no pilot"
  site-url: https://iamnopilot.com
  favicon: ./static/favicon.ico
  open-graph: true
  twitter-card:
    creator: "@i_am_no_pilot"
    image: /static/orange-hat.png
    card-style: summary

  navbar:
    logo: ./static/orange-hat.png
    pinned: true
    search: false

format:
  html:
    theme: 
      light: united
    css: styles.css
    toc: true



